### PR TITLE
Added deepscan tool to readme

### PR DESCRIPTION
**Pull request by mingminggl**
DeepScan is an advanced static code analysis tool that helps us maintain high code quality and catch potential issues in our JavaScript codebase. This can be viewed in the Deepscan section of the readme file.

check it out here: https://github.com/CMU-313/fall23-nodebb-fam/tree/deepscan#deepscan-code-analysis

### CODE REVIEW

**Comment by mingminggl** [comment]
Screenshot 2566-10-27 at 16 24 44
Deepscan is also visible in GitHub workflow as seen here

**Comment by mingminggl** [comment]
Screenshot 2566-10-27 at 16 32 15

**Comment by mingminggl** [comment]
We were able to resolve 2 issues in deep scan. This demonstrated our team's ability to use the tool to identify problems and debug them on the codebase. 
Screenshot 2566-11-01 at 14 56 55

**Comment by adityaganesh0309** [comment]
Looks good, all tests pass! Deepscan has been implemented into the workflow as an extension and runs on each PR. Here, it is configured to force us to fix issues for any new code introduced and will pass if no new issues are introduced. Further description of how it will be used will be present in the design document.

**Pull request merged**
